name: Deploy - Web App [wwwtshandcom] (Azure)

on:
  workflow_dispatch: # Run manually
    inputs:
      tf_action:
        description: "Action: Plan, Apply, Destroy"
        required: true
        default: "Plan"
        type: choice
        options:
          - "Plan"
          - "Plan-Apply"
          - "Destroy"
      deploy_env:
        description: "Environment: dev, tst, prd"
        required: true
        default: "dev"
        type: choice
        options:
          - "dev"
          - "tst"
          - "prd"

  push: # Commits
    paths:
      - "environments/azure/workloads/swa-wwwtshandcom"
      - ".github/workflows/azure-workload-wwwtshandcom.yml"
      - "modules/azure/app-web-staticwebapp"
    branches:
      - main
  
  pull_request: # PR
    paths:
      - "environments/azure/workloads/swa-wwwtshandcom"
      - ".github/workflows/azure-workload-wwwtshandcom.yml"
      - "modules/azure/app-web-staticwebapp"
    branches:
      - main

permissions:
  id-token: write # Required for OIDC auth
  contents: read
  issues: read

jobs:
  deploy_infra_swa_wwwtshandcom:
    name: "Deploy: Infra - WebApp [wwwtshandcom] (Azure)"
    runs-on: ubuntu-latest
    timeout-minutes: 10  # The entire job will fail if it runs longer than 'x' minutes.
    environment: azure-wrk-wwwtshandcom # Name of the Github environment.
    defaults:
      run: # Set job defaults for 'run' commands.
        working-directory: ./environments/azure/workloads/swa-wwwtshandcom
    env:
      # Backend (IaC subscription)
      TF_BACKEND_RG: ${{ vars.TF_BACKEND_RG }} # Backend: Resource Group
      TF_BACKEND_SA: ${{ vars.TF_BACKEND_SA }} # Backend: Storage Account
      TF_BACKEND_CONTAINER: ${{ vars.TF_BACKEND_CONTAINER }} # Backend: Blob Container
      TF_BACKEND_KEY: ${{ vars.TF_BACKEND_KEY }} # Backend: State file name

      # Azure OIDC Auth
      ARM_USE_OIDC: true
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }} # Azure: Tenant ID
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }} # Azure: Service Principal ID
      ARM_SUBSCRIPTION_ID_IAC: ${{ secrets.ARM_SUBSCRIPTION_ID_IAC }} # Azure: Subscription for IaC Backends.
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }} # Azure: Subscription for resources.

      # Github PAT Auth
      GH_PAT_TOKEN: ${{ secrets.GH_PAT_TOKEN }} # Required by Terraform provider to manage environments.

      # Cloudflare Config
      CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_TSHANDCOM_ID }}
      CLOUDFLARE_ZONE_TOKEN: ${{ secrets.CLOUDFLARE_ZONE_TSHANDCOM_TOKEN }}

      # Determine which steps should be run based on inputs and commits or PRs.
      RUN_PLAN: ${{ github.event_name == 'push' || github.event_name == 'pull_request' || github.event.inputs.tf_action == 'Plan' || github.event.inputs.tf_action == 'Plan-Apply' }}
      RUN_APPLY: ${{ github.event.inputs.tf_action == 'Plan-Apply' }}
      RUN_DESTROY: ${{ github.event.inputs.tf_action == 'Destroy' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.0

      - name: Terraform Init
        timeout-minutes: 5  # This step will fail if it runs longer than 'x' minutes.
        run: |
          terraform init \
          -backend-config="resource_group_name=$TF_BACKEND_RG" \
          -backend-config="storage_account_name=$TF_BACKEND_SA" \
          -backend-config="container_name=$TF_BACKEND_CONTAINER" \
          -backend-config="key=$TF_BACKEND_KEY" \
          -backend-config="subscription_id=$ARM_SUBSCRIPTION_ID_IAC"

      - name: Create Cloudflare Config File
        run: |
          cat <<EOF > cloudflare.tfvars
          cloudflare_config = {
            "zone_id": "$CLOUDFLARE_ZONE_ID",
            "zone_token": "$CLOUDFLARE_ZONE_TOKEN"
          }
          EOF

      - name: Terraform Plan
        if: env.RUN_PLAN == 'true'
        timeout-minutes: 5  # This step will fail if it runs longer than 'x' minutes.
        run: |
          terraform plan -out=terraform.tfplan -var-file=prod.tfvars \
          -var-file=cloudflare.tfvars \
          -var="subscription_id=$ARM_SUBSCRIPTION_ID" \
          -var="github_pat=$GH_PAT_TOKEN"
        
      - name: Terraform Apply
        if: env.RUN_APPLY == 'true'
        timeout-minutes: 15 # Fail if it runs longer than 'x' minutes.
        run: |
          terraform apply --auto-approve terraform.tfplan
    
      - name: Terraform Destroy
        if: env.RUN_DESTROY == 'true'
        timeout-minutes: 15 # Fail if it runs longer than 'x' minutes.
        run: |
          terraform destroy --auto-approve -var-file=prod.tfvars \
          -var-file=cloudflare.tfvars \
          -var="subscription_id=$ARM_SUBSCRIPTION_ID" \
          -var="github_pat=$GH_PAT_TOKEN"
